### ISSUE TITLE
Figure out Doxygen to generate documentation

### ISSUE THREAD

**Issue by DanilaFoxPro** [DanilaFoxPro/Unotu#1]
There are a lot of Doxygen-formatted comments in the source code, but Doxygen isn't configured and so documentation isn't generated. Would be nice to have this thing figured out.

**Comment by N-Harsha** [comment]
i am a newbie and want work on this issue so please could you point me in the right direction

**Comment by DanilaFoxPro** [comment]
> 
> 
> i am a newbie and want work on this issue so please could you point me in the right direction

Newbie to Github, C++, CMake, or Doxygen? If you're a newbie to C++, I'm not sure that's a good first issue to work on. I would start with reading documentation and searching the web for other useful information if I were to attempt this issue.

Some relevant documentation links:

- [Doxygen](https://www.doxygen.nl/manual/index.html).
- [CMake](https://cmake.org/cmake/help/v3.5/).

Also this [article](https://vicrucann.github.io/tutorials/quick-cmake-doxygen/) seems like a good practical example.

**Comment by N-Harsha** [comment]
@DanilaFoxPro I am new to github and I don't have any knowledge about Doxygen and CMake I will make sure to read the documentation you sent. It would be helpful if you can guide this issue.

**Comment by N-Harsha** [comment]
Thanks for responding to my first comment.

**Comment by DanilaFoxPro** [comment]
Done on `dev` branch.
